Controllers/DepartmentsController.cs
using StaffManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StaffManagementSystem.Controllers
{
    public class DepartmentsController : Controller
    {
        // GET: Departments
        public ActionResult Department()
        {
            using (StaffMgtSysDbEntities db = new StaffMgtSysDbEntities())
            {

                var dept = db.DepartmentTbs.ToList();
                return View(dept);
            }
            
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DepartmentsModel department)
        {
            DepartmentTb dept = new DepartmentTb()
            {
                DeparmentTbName = department.DeparmentTbName,
                departmentTbDescription = department.departmentTbDescription,
                createdBy = department.createdBy,
                CreatedOn = DateTime.Now,
                UpdatedBy = department.UpdatedBy,
                UpdatedOn = DateTime.Now
            };
            if (ModelState.IsValid)
            {
                using (StaffMgtSysDbEntities db = new StaffMgtSysDbEntities())
                {
                    db.DepartmentTbs.Add(dept);
                    db.SaveChanges();
                    ModelState.Clear();
                    ViewBag.Message = "Department created successfully";
                }
            }
            
            return View();
        }
        public ActionResult Edit(int id)
        {
            using(StaffMgtSysDbEntities db = new StaffMgtSysDbEntities())
            {
                var edit = db.DepartmentTbs.FirstOrDefault(m=>m.DepartmentTbId == id);
                return View(edit);
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DepartmentTb department)
        {
            if (ModelState.IsValid)
            {
                using(StaffMgtSysDbEntities db = new StaffMgtSysDbEntities())
                {
                    db.Entry(department).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Department");
                }
            }
            return View(department);
        }
    }
}

Views/Departments/Create.cshtml
@model StaffManagementSystem.Models.DepartmentsModel

@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        
        @using (Html.BeginForm("Create", "Departments", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Create Departments</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DeparmentTbName, new { htmlAttributes = new { @class = "form-control", placeholder="Department Name"} })
                        @Html.ValidationMessageFor(model => model.DeparmentTbName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                   
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.departmentTbDescription, new { htmlAttributes = new { @class = "form-control", placeholder = "Department Description" } })
                        @Html.ValidationMessageFor(model => model.departmentTbDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.createdBy, new { htmlAttributes = new { @class = "form-control" , placeholder = "Created by" } })
                        @Html.ValidationMessageFor(model => model.createdBy, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" , placeholder = "Updated by" } })
                        @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Department")
        </div>
    </div>
</div>

Views/Departments/Department.cshtml
@model IEnumerable<StaffManagementSystem.Models.DepartmentTb>

@{
    ViewBag.Title = "Department";
}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <h2>Department</h2>

        <p>
            <button class="btn btn-small" style="background-color:green; color:white;">@Html.ActionLink("Add New", "Create")</button>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DeparmentTbName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.departmentTbDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.createdBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedBy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdatedOn)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeparmentTbName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.departmentTbDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.createdBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedOn)
                    </td>
                    <td>
                        <button class="btn btn-small" style="background-color:green; color:white;">@Html.ActionLink("Edit", "Edit", new { id = item.DepartmentTbId })</button>
                        <button class="btn btn-small" style="background-color:green; color:white;">@Html.ActionLink("Delete", "Delete", new { id = item.DepartmentTbId })</button>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Views/Departments/Edit.cshtml
@model StaffManagementSystem.Models.DepartmentTb

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Department</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.DepartmentTbId)

                <div class="form-group">
                    @Html.LabelFor(model => model.DeparmentTbName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DeparmentTbName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DeparmentTbName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.departmentTbDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.departmentTbDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.departmentTbDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.createdBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.createdBy, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.createdBy, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.UpdatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UpdatedOn, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UpdatedOn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Department")
        </div>
    </div>
</div>